# -*- coding: utf-8 -*-
"""Handwritten.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-0HgjJAvAnZGVM429-KdgHvRSJSjW2u
"""

!pip install tensorflow

# Commented out IPython magic to ensure Python compatibility.
from tensorflow import keras
from tensorflow.keras import datasets
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np
from tensorflow.keras import datasets

(X_train,y_train),(X_test,y_test)=datasets.mnist.load_data()

from tensorflow.keras import datasets
datasets.mnist.load_data()

len(X_train)

X_train[0]

X_train.shape

len(X_test)

type(X_train)

X_train[0].shape

X_train[0]

plt.matshow(X_train[0])

plt.matshow(X_train[1])

plt.matshow(X_train[2])

X_train_flattened=X_train.reshape(len(X_train),28,28)
X_test_flattened=X_test.reshape(len(X_test),28,28,1)

X_train.reshape(len(X_train),28,28)

y_train[1]

X_train_flattened=X_train.reshape(len(X_train),28,28)
X_test_flattened=X_test.reshape(len(X_test),28,28)

plt.matshow(X_train_flattened[0].reshape(28,28))

X_train_flattened[0]

# elbow method, kmins clustaring
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_flattened, y_train)

knn.score(X_train_flattened,y_train)

from sklearn.neighbors import KNeighborsClassifier

X_train_flattened = X_train.reshape(X_train.shape[0],-1)
X_test_flattened = X_test.reshape(X_test.shape[0],-1)

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train_flattened, y_train)

knn.score(X_train_flattened,y_train)

knn.predict(X_test_flattened)

from PIL import Image
img = Image.open("mod.jpeg")
img.save("mod.png")
print("Converted successfully!")

import cv2

X_train[6].shape

h, w =X_test[6].shape[:2]

import cv2
center=(w/2 ,h/2)
mat=cv2.getRotationMatrix2D(center,90,1)
rotimg=cv2.warpAffine(X_test[6],mat,(h,w))

plt.matshow(rotimg)

rotimg.shape

rotimg=rotimg.reshape(1,28*28)

import pandas as pd
df=pd.DataFrame(rotimg)
df

knn.predict(df)

modified_image=cv2.imread("/content/mod.png",cv2.IMREAD_GRAYSCALE)
print(modified_image)

plt.imshow(modified_image,cmap='gray')

plt.imshow(modified_image)

plt.imshow(img_resized)

img_resized=cv2.bitwise_not(modified_image)
img_resized